### ISSUE TITLE
Fade not applying consistently

### ISSUE THREAD

**Issue by cadenkriese** [kerudion/chunksfadein#10]
There is inconsistent chunk fading when using the mod [Bobby](https://github.com/Johni0702/bobby). Chunk animations seem to work correctly, though there may also be issues there. I've included videos of both for reference.

# Fade Example
https://user-images.githubusercontent.com/13630061/208281316-df31433b-0d06-4a57-9051-e777dcc9091b.mp4
# Animate Example
https://user-images.githubusercontent.com/13630061/208281324-8a9fbe51-bd35-422c-875c-2731d17d412f.mp4

# Client Details
Minecraft: 1.19.3
JDK: Temurin-19.0.1+10
Quilt: 0.17.8
Chunks Fade In: 1.0.0-1.19.3
Bobby: 4.0.3

**Comment by kerudion** [comment]
Hello!
My mod fades chunks in the same order as they are loaded to the world, so that means that bobby loads chunk in this strange order. Can you please include a video of the same chunks, but with fading turned off?

**Comment by cadenkriese** [comment]
No problem; here's a recording with the animations turned off.

https://user-images.githubusercontent.com/13630061/208315703-265285b6-bc88-4319-b549-2b8e64f79dec.mp4

**Comment by kerudion** [comment]
Hmm, they're still loading in a strange order here. Does this bug happen without the mod even loaded?

**Comment by cadenkriese** [comment]
I may have jumped the gun by calling this a Bobby compatibility issue; here it is with just Sodium and Fade In Chunks.

https://user-images.githubusercontent.com/13630061/208324453-3d8f10a4-56b2-4a8a-a2d9-548f43ce96fa.mp4

**Comment by kerudion** [comment]
Honetly, I don't see any problem here. The fade time may vary a little due to taking frame time in microseconds and not in milliseconds. About strange load order, I've tested a bit and it appears even with only sodium installed.

**Comment by cadenkriese** [comment]
Ohh, it makes much more sense now. The mod is using fog color rather than the skybox color behind the chunk, which would be much more complicated and intensive, I assume. That allows me to see the chunks pop in, which I was reporting as a bug.

**Comment by theRookieCoder** [comment]
If you leave the fog on, I'd recommend a mod like [Clear Skies](https://modrinth.com/mod/clear-skies)

**Comment by kerudion** [comment]
Also chunks for some reason can't be transparent. About using skybox, I don't knew at the start how to use it, so I decided to just use fog color. Now I maybe can try to use it instead of fog.
