### ISSUE TITLE
[BUG]: Chunks fade in requires Sodium version 0.6.0-beta.4, but this version does not appear in the version released by Sodium

### ISSUE THREAD

**Issue by StarsShine11904** [kerudion/chunksfadein#101]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

Sodium 0.6.0-beta.4 is not in minecraft 1.21,Can you please cancel the tag requirement for this version?

### Steps to reproduce

Just view the mod version page directly

[Sodium](https://modrinth.com/mod/sodium/versions?g=1.21)

### Logs

[Loglink](https://mclo.gs/MD2iVcl#L347)

**Comment by kerudion** [comment]
Hi! Fixed in v2.0.2-1.21.
