### ISSUE TITLE
[BUG]: performance lose even when not loading chunks

### ISSUE THREAD

**Issue by shinycolororange** [kerudion/chunksfadein#102]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

performance lose even when not loading chunks / fade off, anmation on. around 30% less fps

### Steps to reproduce

stand still after all chunks are loaded with the mod and without

**Comment by Felix14-v2** [comment]
Please, provide screenshots to demonstrate the issue. We can't investigate a problem with zero technical information.

**Comment by kerudion** [comment]
Hi! Also, what mods are you using? Are you using shaders? What is your config? Is there a lot of entities nearby? Does this worsen with time? Does this happen if you turn off "mod enabled"? Can you provide a video of this happening?

**Comment by shinycolororange** [comment]
First off, I’d like to apologize for my earlier report—it wasn’t very clear. I’ve now done more testing to narrow down the issue and provide better information.

In my original test on a modpack, I noticed my average FPS dropped from 200 to 140, which is a big hit when using shaders. To make sure it wasn’t specific to the modpack, I recreated the issue on a mostly vanilla setup with minimal mods.
Mods Used

    Cloth Config
    Entity Culling
    Fabric API
    FerriteCore
    ImmediatelyFast
    IrisShader
    Lithium
    Mod Menu
    ModernFix
    Sodium
    TextPlaceholder API

Issue

With these mods installed and some small setting changes (Animation: ON, Fade OFF for Far and Near), my FPS consistently drops by around 200. The screenshots I’ve included show the difference clearly and how reproducible it is.

Thanks for taking the time to look into this! 
![javaw exe Screenshot 2024 11 22 - 11 36 25 71](https://github.com/user-attachments/assets/ae294e2e-d16a-4c43-a49c-ecc01a2d600f)
![javaw exe Screenshot 2024 11 22 - 11 38 16 50](https://github.com/user-attachments/assets/6d292537-11f7-4183-8187-725486bf66a4)

**Comment by kerudion** [comment]
Sorry for late response. I did some optimizations, can you try with this version?
[chunksfadein-fabric-2.0.3-1.21-dev.zip](https://github.com/user-attachments/files/17966263/chunksfadein-fabric-2.0.3-1.21-dev.zip)

Also, please use [this mod](https://modrinth.com/mod/fpsdisplay) to see FPS count, because the F3 menu can decrease it a lot.

**Comment by shinycolororange** [comment]
Hey, after doing some testing, the jar you gave me did fix the problem with shaders 230, consistently with and without! In CPU-limited scenarios, there is still a little variation, but at my high FPS, I’m not sure if it’s just normal variation: 1500–1410 without, and 1360–1410 with.

**Comment by kerudion** [comment]
Glad to hear it! Then I'll release it soon
