### ISSUE TITLE
Loading issues on 1.19.3

### ISSUE THREAD

**Issue by cadenkriese** [kerudion/chunksfadein#13]
I'm getting a broken loading loop with only Sodium and Chunks Fade In installed on Quilt 0.17.8 for Minecraft 1.19.3. I get a hanging loading screen with the other 39 mods installed.

# Only Sodium and Chunks Fade In

https://user-images.githubusercontent.com/13630061/209584825-3522b852-2f5e-48d3-834a-d85e71a95b13.mp4

With only Sodium and Chunks Fade In installed, the loading screen loops.
[Logs can be found here.](https://mclo.gs/J4SbIv3)

# All 41 mods installed

https://user-images.githubusercontent.com/13630061/209585237-7b111151-fc12-4dd2-8c92-a665ae6fb374.mp4

Whereas with all mods installed, the loading screen hangs.
[Logs for this test can be found here.](https://mclo.gs/7TaWhAS)

**Comment by Vzurxy** [comment]
Can confirm, happening since newest 2.0.0 update

**Comment by kerudion** [comment]
Can you please check this issue in v2.0.1-1.19.3 release?

**Comment by Vzurxy** [comment]
Looks like it is working now with v2.0.1

**Comment by cadenkriese** [comment]
It works for me as well; thank you for the quick fix!

**Comment by kerudion** [comment]
No problem :)
