### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by XAURAVUS** [kerudion/chunksfadein#15]
Seems to only occur with v2.0.0, as my game does not crash when v1.0.0 is loaded. I am running a heavily modified client, but there are no server side mods in my instance. Crash report is attached below 👍
[crash-2022-12-26_16.23.15-client.txt](https://github.com/kerudion/chunksfadein/files/10305089/crash-2022-12-26_16.23.15-client.txt)

**Comment by kerudion** [comment]
Essentially, a duplicate of #13
