### ISSUE TITLE
Fade speed is refresh rate dependent

### ISSUE THREAD

**Issue by sisby-folk** [kerudion/chunksfadein#2]
I figure you already knew about this one, but just in case!

Because the fadeCoeff is updated every frame, 144hz monitors fade chunks in significantly faster than 60hz monitors.

https://user-images.githubusercontent.com/55819817/205536448-0d778cfe-5465-449d-aaa7-0717afe5177c.mp4

If you have any interest in making the fade speed configurable, this would be necessary first ^^

**Comment by kerudion** [comment]
Hi again!
I'll fix this by saving last frame time, then calculating delta between current and past frames and finally using this delta to calculate fadeCoeff change
