### ISSUE TITLE
Crashing when using old shaders & disabled mod issue.

### ISSUE THREAD

**Issue by DoTrONoL** [kerudion/chunksfadein#23]
Tested with mod disabled and it doesn't crash when using only Iris 1.5 at 1.19.2 (only lens flare works and everything else is black).
https://mclo.gs/9zuoo4S
**Expected behavior:** Don't crash.
**Additional Info:** Don't crash if mod is disabled in _Mod Menu_.

&

When trying to use the Iris with _Chunks Fade In_ disabled in _Mod Menu_, it does a world rendering issue, I just can't see nothing at all, everything is bloom/white, only lights are rendered and the world become invisible.

https://i.imgur.com/SGkZqEO.png

**Comment by kerudion** [comment]
Can you please post full logs?

**Comment by DoTrONoL** [comment]
Log of the bug is only this that'd posted at 2nd line. You mean, you want the log for the "disabled ver" of the _chunks_? I'll provide u soon.

**Comment by kerudion** [comment]
I mean full version of https://mclo.gs/9zuoo4S

**Comment by DoTrONoL** [comment]
Crash Report: https://mclo.gs/wksseoi
Log: https://mclo.gs/3VLdCzA

**Comment by kerudion** [comment]
"RudoPlays Shaders" aren't working even with Sodium and Iris only. I've fixed issue with shaders when mod is disabled and also a bit improved fading with shaders.
