### ISSUE TITLE
Does not load some chunks

### ISSUE THREAD

**Issue by seriousfreezing** [kerudion/chunksfadein#24]
![image](https://user-images.githubusercontent.com/66693072/213922178-8af12848-3de0-4757-a730-98a0ca7230a4.png)

**Comment by kerudion** [comment]
Does this issue exist without Chunks fade in?

**Comment by seriousfreezing** [comment]
I checked and took the mod off and it didn't work.
So apparently it was not the mod's fault, I tried F3 + A, I restarted the game, I created a new map and still have the same problem.

I even put Carpet-fixes and other mods and nothing.

I will close the issue, even though the problem started because of the addition of the Fade Chunks mod

**Comment by kerudion** [comment]
Okay. Personally, I think that it can be Sodium issue and if you don't have it's latest version, you can try to download it
