### ISSUE TITLE
Game Crashed while Enabling Shaderpack.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [kerudion/chunksfadein#26]
Minecraft Version: 1.19.3
ChunkFadeIn Version: [v2.0.8-1.19.3](https://github.com/kerudion/chunksfadein/releases/tag/v2.0.8-1.19.3)
Iris Shader Version: 1.5.2
Shaderpack: KappaRT P16b

Here is the log and the crash report.
[latest.log](https://github.com/kerudion/chunksfadein/files/10685013/latest.log)
[crash-2023-02-08_19.30.19-client.txt](https://github.com/kerudion/chunksfadein/files/10685014/crash-2023-02-08_19.30.19-client.txt)

**Comment by kerudion** [comment]
Fixed in https://github.com/kerudion/chunksfadein/commit/0cd0ae4ebf0a905f3dca03a9e011ea7532692deb, after some time I'll also port these changes to other branches.
Also note that there can be some visual glitches with fading in some shaders, but animation works fine
