### ISSUE TITLE
[Issue] Invisible Glow Squids

### ISSUE THREAD

**Issue by Nekkok** [kerudion/chunksfadein#28]
A weird issue around glow squid (and presumably other mods) is happening to me. At certain altitudes, glow squids are invisible. This happens between Y 30-50 aprox. I made sure that this mod was the one causing it and after disabling it I can confirm it's the responsible in my long long mod list. I'm attaching it so maybe you can find a compatibility issue.

Thank you! Hope you can find a solution because I can't play without your mod : )
[modlist.txt](https://github.com/kerudion/chunksfadein/files/10798542/modlist.txt)

**Comment by kerudion** [comment]
Hi! Does this issue appear with only Sodium and Chunks fade in? Also, at what Y are glow squids and at what Y are you?

**Comment by StarsDeath2938** [comment]
> Hi! Does this issue appear with only Sodium and Chunks fade in? Also, at what Y are glow squids and at what Y are you?

Both entity not rendering at all in ocean, even player model in third person. I confirmed.
Entity Rendering not worked in these chunks where only water and transport blocks. place a block in these chunk make it work currently.
I haven't tested that if it appear with only sodium and fade in but i remove almost all render-related mod in my pack, it still appears.

**Comment by kerudion** [comment]
Fixed in upcoming release
