### ISSUE TITLE
With shaders enabled, chunks fade / pop up on a random order

### ISSUE THREAD

**Issue by RaptaG** [kerudion/chunksfadein#29]
**What is the issue?**
When using a shader, chunks animate on a random order and not the once on the edge of the render

**Conditions to reproduce**
Install Chunks Fade In and Iris and use the [Make Up Ultra Fast](https://modrinth.com/shader/makeup-ultra-fast-shaders) shader.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
(I think) Yes.

**Full Minecraft logs**
I can't upload them right now, though I think there's no useful into about this issue there.

**Comment by kerudion** [comment]
Also fixed in upcoming update

**Comment by RaptaG** [comment]
Lesgoo
