### ISSUE TITLE
Crashes with iris when shaders are enabled.

### ISSUE THREAD

**Issue by sisby-folk** [kerudion/chunksfadein#3]
[latest.log](https://mclo.gs/FNCvHG1)

I figure the mod would need to disable itself somehow when shaders are enabled, but I'm not actually sure how this would work with the shader patcher. (Seeing as you can enable iris shaders mid-game) - Though i might be assuming the issue is more widespread than it is, and there just needs to be a nullcheck for the setter 🤷

**Comment by kerudion** [comment]
Partially fixed in commit [e1be700](https://github.com/kerudion/chunksfadein/commit/e1be700cbc039b07e279edc7a47e1ceb25382c57)

**Comment by kerudion** [comment]
Fully fixed in [2b6fa1d](https://github.com/kerudion/chunksfadein/commit/2b6fa1d0154d96fc1c823096369a42a0f485cb4c)!

**Comment by ViTulyankin** [comment]
WOW!

**Comment by zndrmn** [comment]
legend
