### ISSUE TITLE
Crashes with rethinking voxels

### ISSUE THREAD

**Issue by Aces-and-Jacks** [kerudion/chunksfadein#31]
**What is the issue?**
*Game crashes when I enable shaders*

**Conditions to reproduce**
*When this mod is installed*

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes*

**Full Minecraft logs**
*Insert a link to log file (Remember! Not crash report! Very often a crash report don't even have the cause of issue)*
https://mclo.gs/KHtCmnR

Not sure what else to put here besides the crash report

**Comment by kerudion** [comment]
This issue is very hard to fix, because all shaders have unique code and output/input variables. I'll try to make it compatible, but this will not guarantee compatability with all shaders.

**Comment by Aces-and-Jacks** [comment]
Got it. Well either way thanks for trying a fix. If it doesn't work I'd understand

**Comment by lightlysmile** [comment]
same thing happened with KappaPT
https://mclo.gs/nrL56JV

**Comment by RedGreenBlue09** [comment]
Also crashes with LS RenderPearl.
Many errors in the log but only the last one seems related.
[latest.log](https://github.com/kerudion/chunksfadein/files/11345973/latest.log)

**Comment by kerudion** [comment]
Fixed in https://github.com/kerudion/chunksfadein/commit/0cd0ae4ebf0a905f3dca03a9e011ea7532692deb, after some time I'll also port these changes to other branches

**Comment by RedGreenBlue09** [comment]
The latest update still crashes with LS RenderPearl though.
