### ISSUE TITLE
Chunk Fading Taking Too Long

### ISSUE THREAD

**Issue by eithli** [kerudion/chunksfadein#33]
With the 1.19.4 release of this mod, a new bug has happened. Chunks are just taking too long to fade in.

Here's an example;

I'm going to load up a world and time the fade in animation.

Here's after 10 seconds: 
![image](https://user-images.githubusercontent.com/109933737/225432628-3bcc2b8b-29ca-402f-b3e0-8641e57796b0.png)

Here's after 30 seconds:
![image](https://user-images.githubusercontent.com/109933737/225432698-afb2e214-eece-4eec-a82a-daaa4d1acb69.png)

Here's after 1 minute:
![image](https://user-images.githubusercontent.com/109933737/225432924-47cd177b-6d67-47b3-8fd6-2d2637286237.png)

Log:  [latest.log](https://github.com/kerudion/chunksfadein/files/10984199/latest.log)
The list of mods I am using: https://pastebin.pl/view/bdbbe5bb

**Comment by kerudion** [comment]
Oh no, I think I accidentally moved beta changes from 1.19.3 to 1.19.4
