### ISSUE TITLE
Mod button

### ISSUE THREAD

**Issue by forditt** [kerudion/chunksfadein#34]
The mod button does not disappear with the mod menu installed.
Mod Menu ver. - 6.1.0-rc4
Chunks Fade In ver. - 1.0.1
![зображення](https://user-images.githubusercontent.com/105544922/226096533-ff096f98-3826-4c96-9c98-9f6b7fafb845.png)

**Comment by kerudion** [comment]
I've made that because when I tested my mod on 1.19.4, there was no "Mods" button in pause menu

**Comment by theRookieCoder** [comment]
The pause menu mods button is configurable and can be disabled. Anyways modmenu 1.19.4 is still in beta so it should be fixed soon anyways.

**Comment by kerudion** [comment]
Ok, then I'll make this button configurable

**Comment by forditt** [comment]
Thank you 🐢

> Ok, then I'll make this button configurable

**Comment by kerudion** [comment]
Added in [d963610](https://github.com/kerudion/chunksfadein/commit/d96361057b4ba34757245a5edd9e892464ff0b59)
