### ISSUE TITLE
Will cause the entity to not be rendered

### ISSUE THREAD

**Issue by BIGSTUPIDIAM** [kerudion/chunksfadein#35]
**What is the issue?**
*Write here*
Using version 2.0.11, in the dimension of birth, entities including players will not be rendered.
**Conditions to reproduce**
*Write about where and when this issue occurs*
In the game, the animation enabled is turned on outside of the default settings, it will always occur
**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes/No*
Though the Iris is disabled,this issue still happen.
**Full Minecraft logs**
*Insert a link to log file (Remember! Not crash report! Very often a crash report don't even have the cause of issue)*
[latest.log](https://github.com/kerudion/chunksfadein/files/11150598/latest.log)
![2023-04-04_23 58 01](https://user-images.githubusercontent.com/102842855/229851981-3c6f07f3-2286-4104-a4cd-492fcfdfbb78.png)

**Comment by iMoobert** [comment]
I have the same issue- more specifically, in the **Chunks Fade In Settings**, when **Fade Enabled** is set to **No**, reloading the chunks or exiting/re-entering the world causes all entities to become invisible.

Re-enabling **Fade Enabled** to **Yes** immediately solves the issue, without needing to reload chunks.

 ---

**What is the issue?**
 - Entities become invisible after disabling the Fade animation
**Conditions to reproduce**
 - Disable Fade animation and then reload chunks - or - Disable Fade animation, enter world
**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
 - Yes, when only those 3 are installed in the Mods folder, the issue still occurs
**Full Minecraft logs**
 - https://mclo.gs/F6c5f2G - With only the 3 above mods in the folder

Example Screenshots: 

![2023-08-25_18 24 22](https://github.com/kerudion/chunksfadein/assets/55117135/b9a44ecc-9b81-437a-aa2a-c33b3c73f078)

![2023-08-25_18 24 42](https://github.com/kerudion/chunksfadein/assets/55117135/c26ff218-52a4-489b-9144-65cf5f7b5ac4)

**Comment by kerudion** [comment]
This issue was fixed in https://github.com/kerudion/chunksfadein/commit/98016c3c1e5d0da92d94a260a46d96201ae15997, following by other branches. I haven't understood it initially. Thanks for clarification
