### ISSUE TITLE
Incompatible with Iris 1.6.1

### ISSUE THREAD

**Issue by Slooshie1** [kerudion/chunksfadein#36]
**What is the issue?**
*Chunks Fade In causes a shader fallback on Iris 1.6.1*

**Conditions to reproduce**
*Using Iris 1.6.1 RC3 and Chunks Fade In 1.0.2 and IMS says the fix must be done on your side*

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes*

**Full Minecraft logs**
*https://mclo.gs/FfahRB0*

**Comment by kerudion** [comment]
Fixed in [3266503](https://github.com/kerudion/chunksfadein/commit/3266503255fb0d57d54078dda103fea362afa253)
