### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by ryanjrman** [kerudion/chunksfadein#39]
**What is the issue?**
Crash when loading into worlds with the most recent version.

**Conditions to reproduce**
I have quite a few mods installed. However, I have included a crash report and Log. However, it appears as though they say the same thing. Game loads fine, only happens after "joining game" screen appears in single player or on server.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
No, I actually did test this.

**Full Minecraft logs**
*Insert a link to log file (Remember! Not crash report! Very often a crash report don't even have the cause of issue)*
[Crash Report.txt](https://github.com/kerudion/chunksfadein/files/11349524/Crash.Report.txt)
[2023-04-27-5.log.gz](https://github.com/kerudion/chunksfadein/files/11349530/2023-04-27-5.log.gz)

**Comment by kerudion** [comment]
Hi! Looks like Custom Entity Models (CEM) mod is causing this issue. Can you try to join the world without CEM installed and see if it crashed?

**Comment by ryanjrman** [comment]
Sorry its been a while. I updated to the more recent version and got rid of CEM and it seemed to work just fine!
