### ISSUE TITLE
Incompat with Immersive Portals Mod

### ISSUE THREAD

**Issue by Cape-City** [kerudion/chunksfadein#40]
**What is the issue?**
If you have an Immersive Portal active and load into the game, only the entities on the other side will be correctly loaded.
The entities in the area where the player loads into are not visible, but you can hear them.

**Conditions to reproduce**
These mods where active and i created a new 1.19.3 fabric world:

Chunks fade in - kerudion - chunksfadein-v2.0.11-1.19.3.jar
Fabric API - modmuss50 - fabric-api-0.76.1+1.19.3.jar
Immersive Portals - qouteall - immersive-portals-2.5.4-mc1.19.3-fabric.jar
Sodium - jellysquid3_ - sodium-fabric-mc1.19.3-0.4.9+build.23.jar

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
No - also without an active Nether Portal, loading into the world is normal. If you load into the game and the chunk where
the nether portal is active isn't loaded yet, everything is fine too, but if you go towards the portal and the chunk loads,
the entities are unvisible.

In my main profile, i also have iris shaders installed and when i reload the shader, the missing entities are shown again.
Maybe Chunk Fade in just had to do such a kind of refresh, after entering the world...

**Full Minecraft logs**
[latest.log](https://github.com/kerudion/chunksfadein/files/11351575/latest.log)

**Comment by Cape-City** [comment]
The version chunksfadein-v2.0.10-1.19.3.jar seems not having this issue above.

**Comment by kerudion** [comment]
Hmm, if it works in that version, this issue is cause by the new method of fading. I'll look into this issue soon.

**Comment by Cape-City** [comment]
I always try different constallations and always as refernce with a clean MC profile with just the needed mods installed. Hope it's helpfull to find the issue faster ;)

**Comment by kerudion** [comment]
Fixed in 1.20.1 version. Soon will be also fixed in 1.20, 1.19.x and 1.18.x versions.
