### ISSUE TITLE
Incompatability with sodium 0.4.11+build.26

### ISSUE THREAD

**Issue by KidOfCubes** [kerudion/chunksfadein#41]
**What is the issue?**
*Write here*
Crashes with sodium 0.4.11+build.26

**Conditions to reproduce**
*Write about where and when this issue occurs*
When I use sodium 0.4.11+build.26 for 1.19.4 from modrinth.
Crash happens after I load into a world

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes/No*
Yes (tested without iris)

**Full Minecraft logs**
*Insert a link to log file (Remember! Not crash report! Very often a crash report don't even have the cause of issue)*
https://mclo.gs/4EHoVY4

**Comment by kerudion** [comment]
Hi! Already working on this issue.

**Comment by RaptaG** [comment]
> Hi! Already working on this issue.

What's the status of this?
I wanna update my modpack to be compatible..

**Comment by RaptaG** [comment]
This sodium version has been removed, this issue should be closed

**Comment by KidOfCubes** [comment]
Closed due to the removal of sodium 0.4.11
