### ISSUE TITLE
Crash on startup with latest iris/sodium

### ISSUE THREAD

**Issue by cootshk** [kerudion/chunksfadein#43]
Mixin apply issue

logs: https://mclo.gs/s98NxHO

**Comment by Pokethorix** [comment]
yeah im having the same problem

**Comment by cootshk** [comment]
v1.0.2 (was the latest version when I opened the issue)

**Comment by Pokethorix** [comment]
for me im on 1.0.3 1.19.4

**Comment by kerudion** [comment]
Looks like that's Chat Heads problem

**Comment by iMoobert** [comment]
I'm having the same issue and I don't use Chat Heads
Every mod I use is compatible except this one, and I have 118 other downloaded items atm

Logs: https://mclo.gs/6XyXZ3e

**Comment by kerudion** [comment]
This issue really was caused by Chat Heads, but your issue happened because of lazy me who checked the mod in "debug mode" which is launched straight from code development application, rather than in the real game. Now it's fixed though.

**Comment by JosefLitos** [comment]
could a version 3.0.12 updated for 1.20.1 sodium 5.2 fix this?

**Comment by kerudion** [comment]
@JosefLitos The latest version for 1.20.1 and support for Sodium 0.5.1+ is available [here](https://modrinth.com/mod/chunks-fade-in/version/v1.0.3-1.20.1). The 3.0.12 version you are referring to is from the *1.19* branch, as I keep separate version numbering for each compatible Minecraft version range:
- 1.18.x
- 1.19-1.19.2
- 1.19.3
- 1.19.4
- 1.20.x (for Sodium 0.4.x)
- 1.20.1 (for Sodium 0.5.x)

**Comment by JosefLitos** [comment]
@kerudion oh, I thought the versioning goes up as the mod evolves, didn't realize it's per version. Unfortunately I was using the 1.0.3 version and using any shaders always caused a crash with that version (as well as any other for 1.20.1). I tried earlier versions of Iris+Sodium (what I could without dependency issues) and the issue persisted.
I am not sure how I've missed that before, I just don't use shaders that much, but unfortunately I don't know what was the last version it worked for me (I don't use the mod for that long so I've probably never tried it before).

**Comment by kerudion** [comment]
Thanks :) Not all shaders crash, some of them work. For example, MakeUp and Complementary. This is a known issue and I've been trying to fix it for months now. I recently discovered a method that might fix this problem, but I'm still not sure if it will work with all shaders.
