### ISSUE TITLE
Suggestion: Do not animate for subchunks of chunks that are already loaded

### ISSUE THREAD

**Issue by nopeless** [kerudion/chunksfadein#44]
This happens when I am pillaring up. The subchunk would load and the animation would play. This seems unnatural. 

I am willing to write a PR for this

**Comment by Apollogeist** [comment]
Any updates on this? Subchunks still fade in 1.20.4 Fabric.

**Comment by kerudion** [comment]
Hello! I guess this is fixed by setting "Fade near player: NO" and "Animate near player: NO".
