### ISSUE TITLE
crashes with Kappa PT shader

### ISSUE THREAD

**Issue by llMooreyll** [kerudion/chunksfadein#45]
**What is the issue?**
*when switch to the kappa pt,game cashes,i disabled every mod one by one,then i found the chunksfadein cause the crash*

**Conditions to reproduce**
*just enable the kappa pt shader with chunksfadein*

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes*

**Full Minecraft logs**
*https://mclo.gs/pls0LTr*

**Comment by kerudion** [comment]
Fixed in https://github.com/kerudion/chunksfadein/commit/0cd0ae4ebf0a905f3dca03a9e011ea7532692deb, after some time I'll also port these changes to other branches
