### ISSUE TITLE
Sodium 0.5 Update

### ISSUE THREAD

**Issue by piebaker** [kerudion/chunksfadein#47]
**What is the issue?**
CFI is incompatible with the latest version of sodium (0.5)

**Conditions to reproduce**
Update sodium, load CFI

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
Yes

**Full Minecraft logs**
N/A

**Comment by ElPepe6969** [comment]
Same here:
![image](https://github.com/kerudion/chunksfadein/assets/122692226/1e29716d-6e2e-4ab9-b5d7-7e6da7f0a53f)


Also it has the sodium 0.5 listed as a dependency on modrinth
https://modrinth.com/mod/chunks-fade-in/version/v1.0.1-1.20

**Comment by kerudion** [comment]
I'm working on compatibility with Sodium 0.5.x and I hope that I'll finish it soon
>Also it has the sodium 0.5 listed as a dependency on modrinth
https://modrinth.com/mod/chunks-fade-in/version/v1.0.1-1.20

This happens because I did not explicitly set a specific version of Sodium, so Modrinth automatically displays latest one

**Comment by kerudion** [comment]
Fixed in the new version
