### ISSUE TITLE
Axiom and first person model not working with chunks fade in

### ISSUE THREAD

**Issue by reemlife1** [kerudion/chunksfadein#48]
**What is the issue?**
*The Axiom mod doesn't play the animation when joining the world, and First Person Model crashes the game when joining the world when animation setting is on*

**Conditions to reproduce**
*all you need is sodium, chunks fade in ( with animation on ) and first person model or axiom mod*

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*No, iris doesn't change anything *

**Full Minecraft logs**
*First Person Model:

java.lang.NullPointerException: Cannot invoke "com.koteinik.chunksfadein.extensions.RenderSectionExt.getAnimationOffset()" because the return value of "me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.getRenderSection(int, int, int)" is null

Axiom didn't crash at all*

**Comment by kerudion** [comment]
Is it fixed with the new version? FPM works, but I can't launch Axiom myself

**Comment by reemlife1** [comment]
for FPM it is fixed but it still doesn't work with axiom

**Comment by kerudion** [comment]
By the way, what do you mean by `The Axiom mod doesn't play the animation when joining the world`? What animation it should play?

**Comment by kerudion** [comment]
Oh, I got Axiom to work and tested it myself now. Chunks Fade In does not fade-in and animate chunks, that's what you meant. I'll fix this soon.

**Comment by reemlife1** [comment]
yeah, good luck with fixing it

**Comment by kerudion** [comment]
Fixed in [f54dc18](https://github.com/kerudion/chunksfadein/commit/f54dc180d6a52a9c0bfddaca61c348c40452148f). Also note that you need the latest version of Sodium and Axiom.
