### ISSUE TITLE
Game crashes with BSL or Complementary Reimagined Shaders

### ISSUE THREAD

**Issue by Wionsito** [kerudion/chunksfadein#49]
**What is the issue?**
The game crashes when having Chunks Fade In enabled and using the before mentioned shaders.

**Conditions to reproduce**
The game crashes when the world is loading while having the mod enabled and using the before mentioned shaders.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
Yes, Sodium 0.5.0, Iris 1.6.5 and Chunks Fade In 1.0.1

**Full Minecraft logs**
[latest.log](https://github.com/kerudion/chunksfadein/files/12328266/latest.log)

**Comment by kerudion** [comment]
Similar issue appears to occur with a lot of shaders. But sadly I don't know how to fix it now

**Comment by kerudion** [comment]
Fixed in https://github.com/kerudion/chunksfadein/commit/0cd0ae4ebf0a905f3dca03a9e011ea7532692deb, after some time I'll also port these changes to other branches

**Comment by Wionsito** [comment]
> Fixed in [0cd0ae4](https://github.com/kerudion/chunksfadein/commit/0cd0ae4ebf0a905f3dca03a9e011ea7532692deb), after some time I'll also port these changes to other branches

Thanks!
