### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by zndrmn** [kerudion/chunksfadein#5]
I'm like 100% sure that it's a mod conflict
I would be awesome if you're able to fix this somehow
[latest.log](https://gist.github.com/zndrmn/a61e9ba85ec1be0490b3a84e7a226f8e#file-latest-log)
[crash-2022-12-09_16.57.05-client.txt](https://gist.github.com/zndrmn/8f66f4f38572d70ab6254ed7ce94b892#file-gistfile1-txt)

**Comment by haventhadadonutyet** [comment]
Also getting this.

**Comment by theRookieCoder** [comment]
I'm not exactly sure but I think this is an issue with a missing dependency. The mod works for me and I _think_ the missing dependency is in Cloth Config API.

**Comment by theRookieCoder** [comment]
For some reason it works with my full mod list, but doesn't when loaded by itself (with sodium ofc). I tried to narrow it down but every combination I tried ended up with this same error. I think it's some build misconfiguration leading to toml4j not being properly bundled with the mod.

**Comment by theRookieCoder** [comment]
Hah I found it! It turns out that DynamicFPS properly bundles the toml4j jar with it's mod file.

**Comment by theRookieCoder** [comment]
@kerudion your `build.gradle` does use [this `include` like](https://github.com/juliand665/Dynamic-FPS/blob/main/build.gradle#L44) so the library isn't being included in the final jar.

**Comment by zndrmn** [comment]
lmao I had so many mods that I thought it was a mod conflict and I guess it wasn't

**Comment by theRookieCoder** [comment]
> lmao I had so many mods that I thought it was a mod conflict and I guess it wasn't

Lol if anything having more mods increases the likelihood of this issue being fixed 😂

**Comment by kerudion** [comment]
Oh my god, that's my bad. I've never worked with gradle before this mod, only with maven. Thanks @theRookieCoder again :)
