### ISSUE TITLE
Add option to disable fade near player

### ISSUE THREAD

**Issue by ghost** [kerudion/chunksfadein#57]
### What is the suggestion?
Add an option to disable the fade affect on chunks near the player, similar to the option regarding the animation as a whole. This would make the effect more subtle, and only appear on chunks rendering in near the edge of the world.

### Why is it needed?
When loading the world for the first time or turning around rapidly, you often see the fading effect on chunks interrupting your vision. This change would make the experience more uniform, when the disable animation near player option is also enabled.

**Comment by Matz-42** [comment]
Bump on this.
Would be a greatly appreciated feature, having chunks fade in so close to the player just looks weird and is really distracting.

**Comment by kerudion** [comment]
Hello! Added in the new release.
