### ISSUE TITLE
Shaders issue

### ISSUE THREAD

**Issue by Baklet** [kerudion/chunksfadein#58]
**What is the issue?**
All textures turn white
![2023-11-01_16 05 54](https://github.com/kerudion/chunksfadein/assets/149591689/cf5ecdce-f204-487f-bf7e-1e8f86d77f8b)
**Conditions to reproduce**
When I turn on shaders, the textures break and all the blocks become white textures
No resourcepacks on
**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
Yes
**Full Minecraft logs**
https://mclo.gs/ncEdRTc

**Comment by kerudion** [comment]
Duplicate of https://github.com/kerudion/chunksfadein/issues/54
