### ISSUE TITLE
[1.20.1 FORGE] Incompatible with Sinytra Connector.

### ISSUE THREAD

**Issue by Wanderer70** [kerudion/chunksfadein#59]
While I would have reported this to the Connector Dev, the problem seems to be originating from your mod as it has Sodium as a dependency. The game won't launch because Chunks Fade In requires Sodium and not Embeddium or Rubidium, thus making it impossible to test whether it works on forge too.

I suggest making an experimental version without this restriction, just too see if it works. Chances are it won't, as Embeddium/Rubidium differ from Sodium in many ways and so the game will crash upon joining a world, but that won't be your problem anymore as I will report that to the Connector Dev and see whether it's possible to fix or not.

It would be really cool to have animated chunks on Forge too! :D (I mean, there is Chunk Animator, but it is incompatible with Embeddium/Rubidium and has less features, so yeah, TO THE TRASHBIN!)

**Comment by ChromeTV** [comment]
Actually the mod can works if you delete sodium dependence in the fabric.json using winrar and have embedium and sinytra instaled (i have test that using 1.20.1 release and works fine even using oculus shaders), so yeah, looks like is possible make it tecnically possible to work.

**Comment by cpof-tea** [comment]
@ChromeTV

> Actually the mod can works if you delete sodium dependence in the fabric.json using winrar and have embedium and sinytra instaled (i have test that using 1.20.1 release and works fine even using oculus shaders), so yeah, looks like is possible make it tecnically possible to work.

That works, thanks!

**Comment by ChromeTV** [comment]
you welcome, but i think would be great to have that compatibility intagred in the mod for make more easy everything, but guess only have to wait to next update

**Comment by kerudion** [comment]
Hi!
Currently I have no "good" way of fixing this issue solely inside the mod sadly.
So, instead I've made a [little guide](https://github.com/kerudion/chunksfadein#compatibility-with-forge) that explains how to fix it

**Comment by BoardAnims** [comment]
> Hi! Currently I have no "good" way of fixing this issue solely inside the mod sadly. So, instead I've made a [little guide](https://github.com/kerudion/chunksfadein#compatibility-with-forge) that explains how to fix it

Is there a way to have both this mod AND nvidium to run in forge? because the fabric_loader_dependencies.json only seems to accept "overriding" one mod at a time.
It could be as simple as adding a "{}" somewhere but idk how JSON works lol

I tried this but it still crashes my game...

> {
  "version": 1,
  "overrides": {
    "chunksfadein": {
      "+depends": {
        "embeddium": ">0.2.18+mc1.20.1"
      },
      "-depends": {
        "sodium": "IGNORED"
      }
    }
  }
}
{
  "version": 1,
  "overrides": {
    "nvidium": {
      "+depends": {
        "embeddium": ">0.2.18+mc1.20.1"
      },
      "-depends": {
        "sodium": "IGNORED"
      }
    }
  }
}
