### ISSUE TITLE
Settings Icon [1.20.4]

### ISSUE THREAD

**Issue by CrypticVerse** [kerudion/chunksfadein#63]
**Settings Icon is not right**
*I was playing in a fabric 1.20.4 world, and went to configure the chunks fade in settings, and the icon was the missing texture black and purple icon*

**Conditions to reproduce**
1. Have a Fabric 1.20.4 environment, with chunks fade in 1.0.0

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
Yes
[latest.log](https://github.com/kerudion/chunksfadein/files/13694277/latest.log)

Pic is attached
![bug](https://github.com/kerudion/chunksfadein/assets/143554094/919fc0e8-2d9b-494f-9a0a-20f8bb7203da)

**Comment by CrypticVerse** [comment]
This bug does not exist in 1.20.2

**Comment by CrypticVerse** [comment]
Hello?

**Comment by kerudion** [comment]
Hi!
I'm really sorry for not actively maintaining this mod lately. I want to assure you that I still care about this mod and haven't abandoned it. Just to be short, I may not be able to fix non-critical bugs as quickly as before.
I truly apologize for any inconvenience this may cause

**Comment by kerudion** [comment]
Fixed in new version
