### ISSUE TITLE
With "Animate near player: NO", blocks can still go through the camera

### ISSUE THREAD

**Issue by YoshiRulz** [kerudion/chunksfadein#68]
**What is the issue?**
Title. I'm guessing this is because "near" is calculated as a sphere rather than a cylinder.

**Conditions to reproduce**
Disable "Animate near player" and press F3+A. Most noticeable underground or in the Nether.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
No? Issue template unclear.

**Full Minecraft logs**
N/A

**Comment by kerudion** [comment]
Hi! This was fixed when I made "Animate near player" check coordinates cylindrically, rather than spherically.
