### ISSUE TITLE
doesn't render lecterns correctly

### ISSUE THREAD

**Issue by yarom1342** [kerudion/chunksfadein#69]
What is the issue?

when you place lecterns their upper part has some weird render glitch, you can't miss it. (if it doesn't happen to you then it's probably because i have a lot of other mods installed so take that into account i guess)

Conditions to reproduce

just place it everywhere as far as i can tell

Does this issue appear only with Sodium, Iris and Chunks Fade In?

yes, tried to run the mod without sodium. says it has to have it. tried to run it only with sodium (moved out my iris mod and all the other sodium addons) still happened.

Full Minecraft logs:

[latest.log](https://github.com/kerudion/chunksfadein/files/14411858/latest.log)

(also it says 342 mods but in reality i only have 202 separate mod files so i don't know what's up with that). those mods (most of them) don't change the game that much. mostly a vanilla build with bugfixes and some bit extra so i wouldn't imagine that it's probable to assume it's a problem with some other mod there(i mean in combination with this mod, tried to remove every single one of those 202 mods, it was this mod that caused it). if it is i guess you can ignore all of this lol because it is a lot of mods. (its not a modpack i just put a lot of vanilla friendly mods)

**Comment by kerudion** [comment]
Hi! Unfortunately I can't reproduce this issue using only Sodium, Iris and Chunks Fade In installed. I also haven't found out which mod or resource pack can cause this issue. Can you please try to find out for yourself?

**Comment by yarom1342** [comment]
> Owner
ummm i tried to replicate the issue, it didn't occur. i did delete some mods that i have though still it's weird because i'm certain that i checked the mod only with sodium and moved the rest. maybe i had an older version of chunksfadein though probably not because it wasn't that long ago. i couldn't restore the same config that i had at that time (specifically configs of minecraft not mods) but still it didn't occur again. i guess that maybe one mod just screw up the world that i was in or something so probably you can just forget about it.
if it occurs again sometime i will inform you (:

**Comment by yarom1342** [comment]
> No problem, can I close this issue then?

ummm i guess so, i mean i couldn't replicate it even though i used like 95% the same mods. so yeah probably yes. though still weird that it didn't happen. but yeah i don't see any reason to leave it there. probably too rare or was a one time think lol. sorry for bothering you though i did check it a lot before reporting it, so i have no idea what's changed or what was different lol.
