### ISSUE TITLE
Game crashes when loading shaders

### ISSUE THREAD

**Issue by Aerhtjiz** [kerudion/chunksfadein#70]
**What is the issue?**
*Write here*
when you load the bliss shaders in iris the game crashes after a couple of seconds.
**Conditions to reproduce**
*Write about where and when this issue occurs*
I think it has something to do with the distant horizons 2 beta. 
**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes/No*
yes
**Full Minecraft logs**
*Insert a link to log file (Remember! Not crash report! Very often a crash report don't even have the cause of issue)*
https://www.dropbox.com/scl/fi/bfo9i3y3uqzoacoibsf4p/latest.log?rlkey=anhwmt5s6o5sebdkwvwfezu02&dl=0

**Comment by kerudion** [comment]
Hi, this looks like it's because you are using Iris version 1.7-alpha. I will fix compatibility with it after a full 1.7 release, because a lot can change while it's still in development
