### ISSUE TITLE
[BUG]: The mod does not work with higher versions of Fabric loader

### ISSUE THREAD

**Issue by StarsShine11904** [kerudion/chunksfadein#73]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

Game crashes after installing mod

### Steps to reproduce

This issue can be triggered using loader version: 0.15.10

**Comment by marat2509** [comment]
I support. Also, after updating to the latest version of Fabric Loader the game crashes

Logs: https://mclo.gs/RcwdCT4

**Comment by kerudion** [comment]
Hi!
I couldn't reproduce the issue with fabric loader 0.15.10 by just using Chunks Fade In, Iris, Sodium and Fabric API. But looks like it's related to [this](https://github.com/kerudion/chunksfadein/issues/74) issue, which is related to Crowdin translation library, which is related to YetAnotherConfigLib.

**Comment by marat2509** [comment]
> related to YetAnotherConfigLib

Yes, that's more like it. After updating YACL to the latest version that included the fix of CrowdinTranslate the problem was fixed.
