### ISSUE TITLE
[BUG]: problem with crowdin translate

### ISSUE THREAD

**Issue by nEONcReepER990** [kerudion/chunksfadein#74]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

"problem with crowdin translate" Said by the creator of YetAnotherConfigLib also reported on [their](https://github.com/isXander/YetAnotherConfigLib/issues/166) github

### Steps to reproduce

just install [YetAnotherConfigLib](https://modrinth.com/mod/yacl) v3.4.0 (latest as of writing)

### Logs

[latest.log](https://github.com/kerudion/chunksfadein/files/15098758/latest.log)

### Crash Report

[crash-2024-04-24_20.16.10-client.txt](https://github.com/kerudion/chunksfadein/files/15098759/crash-2024-04-24_20.16.10-client.txt)

**Comment by Poopooracoocoo** [comment]
Requires https://github.com/gbl/CrowdinTranslate/issues/22 to be fixed.
