### ISSUE TITLE
[BUG]: Iris version 1.7 prevents mod from working on shaders

### ISSUE THREAD

**Issue by Hario337** [kerudion/chunksfadein#79]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

On version 1.7 of Iris, this mod does not work while shaders are active, and no fade or animation plays.
Iris version 1.6.17 and below have no issues and works as normal with and without shaders.
I'm experiencing this using version 1.0.2 of ChunksFadein on MC 1.20.4 with fabric

I found this in the iris 1.7 changelog, so it may be whats causing this issue
![image](https://github.com/kerudion/chunksfadein/assets/39669911/36f78c28-3b49-40b2-9a93-7b8ab481d2f4)

### Steps to reproduce

Opening a world with Iris 1.7 installed and seeing no animation
Opening a world with Iris 1.6.17 installed and seeing the animation working fine

**Comment by kerudion** [comment]
Fixed in 7de3139e167f894ff6707729438135bf5097d3a8
