### ISSUE TITLE
[BUG]: Mod causes mobs rendered inside spawners to be misaligned

### ISSUE THREAD

**Issue by mariberry-hearn** [kerudion/chunksfadein#90]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

As it says in the title:

![image](https://github.com/user-attachments/assets/9d29f8c9-9cb8-4ea7-ad5c-22be44a4f5bb)

In particularly egregious cases, the misalignment gets intense and the spinning mob might even orbit the spawner in a much larger area, which seemingly happens in spawners placed farther from x0 z0

Bug is observed to occur even with just the latest patches for Sodium and CFI

### Steps to reproduce

Simply place a trial/mob spawner and set it up with a spawn egg, or find a naturally generated one

**Comment by kerudion** [comment]
Fixed in the new release
