### ISSUE TITLE
[BUG]: Misaligned armor stand in smithing table UI

### ISSUE THREAD

**Issue by mariberry-hearn** [kerudion/chunksfadein#91]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

As the title says:

![image](https://github.com/user-attachments/assets/a4cc4075-9570-410b-8790-d8839ff6d5bd)

Something in the mod seemingly makes the armor stand's position on the UI scale on the player's current coordinates; at a certain point the armor stand would be cut off and stop rendering altogether. If you pay attention to this clip you can see the armor stand element move as I get pushed by the water:

https://streamable.com/qil80b

Bug is observed to occur even with just the latest patches for Sodium and CFI

### Steps to reproduce

Just open up the smithing table UI

**Comment by kerudion** [comment]
Fixed in the new release
