### ISSUE TITLE
[BUG]: Client Crashes on join

### ISSUE THREAD

**Issue by RyuguDev** [kerudion/chunksfadein#96]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

Client Crashes on join

### Steps to reproduce

Joined a Server

### Logs

https://mclo.gs/gVEBIoC

### Crash Report

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-10-30 10:58:19
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5705(float)" because "$$1" is null
	at knot//net.minecraft.class_4184.method_19321(class_4184.java:55)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1052)
	at knot//net.minecraft.class_757.method_3192(class_757.java:850)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_4184.method_19321(class_4184.java:55)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1052)

-- Uptime --
Details:
	JVM uptime: 128.652s
	Wall uptime: 112.288s
	High-res time: 106.142s
	Client ticks: 128 ticks / 6.400s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 289, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot read field "field_3944" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
	Tracked entity count: 0

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, betterf3, bsvsb, chunksfadein, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, conditional-mixin, continuity, drippyloadingscreen, dynamic_fps, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fancymenu, fbp, forgeconfigapiport, fzzy_config, immediatelyfast, iris, konkrete, lambdynlights, lithium, modernfix, modmenu, moreculling, net_raphimc_viaaprilfools-common, net_raphimc_viabedrock, net_raphimc_vialegacy, notenoughanimations, palladium, particle_core, particlerain, particletweaks, placeholder-api, pride, reeses-sodium-options, rrls, skinlayers3d, sodium, sodium-extra, sodium-no-alerts, sodiumextrainformation, sodiumextras, sodiumleafculling, sodiumoptionsapi, sound_physics_remastered, spruceui, sspb, toadlib, viafabricplus, voicechat, wi_zoom, yet_another_config_lib_v3, zoomify, classic_icons, continuity:default, continuity:glass_pane_culling_fix, file/Prideful Parrots (Pansexual), file/Prideful Parrots (Non-Binary), file/pan.zip, file/FemPack.zip, file/NeverPack.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 203401808 bytes (193 MiB) / 1073741824 bytes (1024 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon (TM) RX 480 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.12027.9001
	Graphics card #1 name: Intel(R) HD Graphics 4000
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 2112.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 10.18.10.5161
	Memory slot #0 capacity (MiB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MiB): 23434.11
	Virtual memory used (MiB): 15008.66
	Swap memory total (MiB): 3072.00
	Swap memory used (MiB): 194.91
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 6874.27, total: 121447.77
	Space in storage for workdir (MiB): available: 6874.27, total: 121447.77
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.8
		betterf3: BetterF3 11.0.2
		bsvsb: Better Sodium Video Settings Button 4.0.0-alpha.0
		chunksfadein: Chunks Fade In 1.0.3-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		drippyloadingscreen: Drippy Loading Screen 3.0.8
		dynamic_fps: Dynamic FPS 3.7.4
			net_lostluma_battery: battery 1.2.0
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fancymenu: FancyMenu 3.3.2
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fbp: FancyBlockParticles 21.1.1.2
		ferritecore: FerriteCore 7.0.2-hotfix
		fzzy_config: Fzzy Config 0.5.6+1.21
			blue_endless_jankson: jankson 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		immediatelyfast: ImmediatelyFast 1.3.0+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		konkrete: Konkrete 1.9.9
		lambdynlights: LambDynamicLights 3.1.2+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		lithium: Lithium 0.14.0-snapshot+mc1.21.1-build.88
		melody: Melody 1.0.10
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.3
		moreculling: More Culling 1.0.0
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mr_animated_doors: Animated Doors 1.21
		notenoughanimations: NotEnoughAnimations 1.7.6
		palladium: Palladium 1.0.9.3
		particle_core: Particle Core 0.2.4+1.21
		particlerain: Particle Rain 2.1.4
		particletweaks: Particle Tweaks 2.0-mc1.21.1
		placeholder-api: Placeholder API 2.4.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		rrls: Remove Reloading Screen 5.0.8+mc1.21.1-fabric
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.6.0-beta.4+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		sodium-no-alerts: Sodium No Alerts 1.0.0+mc1.21.1
		sodiumextrainformation: Sodium Extra Information 2.2-beta.1
		sodiumextras: Sodium Extras 1.0.5
			forgeconfigapiport: Forge Config API Port 21.1.0
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
		sodiumleafculling: Sodium Leaf Culling 1.0.0
		sodiumoptionsapi: Sodium Options API 1.0.5
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sspb: Sodium Shadowy Path Blocks 4.0.0-beta.2
		toadlib: ToadLib 1.1.6
		viafabricplus: ViaFabricPlus 3.4.9
			com_github_oryxel_cubeconverter: CubeConverter 5ae1e90e4f
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.1.0
			com_viaversion_viaversion-common: viaversion-common 5.1.1-20241025.184819-1
			de_florianmichael_classic4j: Classic4J 2.1.1-SNAPSHOT
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.114
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.6.0
			net_lenni0451_mcping: MCPing 1.4.2
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.1
			net_lenni0451_mcstructs-bedrock_text: text 1.2.1
			net_raphimc_minecraftauth: MinecraftAuth 4.1.1
			net_raphimc_viaaprilfools-common: viaaprilfools-common 3.0.4-20241025.171739-1
			net_raphimc_viabedrock: ViaBedrock 0.0.13-20241025.223546-1
			net_raphimc_vialegacy: ViaLegacy 3.0.5-20241025.171620-1
			net_raphimc_vialoader: ViaLoader 3.0.5-20241025.171921-1
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
		voicechat: Simple Voice Chat 1.21.1-2.5.25
		wi_zoom: WI Zoom 1.5-MC1.21.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.2+1.21.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: (off)
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Radeon (TM) RX 480 Graphics GL version 3.2.0 Core Profile Context 22.20.27.09.230330, ATI Technologies Inc.
	Window size: 1680x1050
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), betterf3, bsvsb, chunksfadein, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, conditional-mixin, continuity, drippyloadingscreen (incompatible), dynamic_fps, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fancymenu (incompatible), fbp, forgeconfigapiport, fzzy_config, immediatelyfast, iris, konkrete (incompatible), lambdynlights, lithium, modernfix (incompatible), modmenu, moreculling, net_raphimc_viaaprilfools-common, net_raphimc_viabedrock, net_raphimc_vialegacy, notenoughanimations, palladium, particle_core, particlerain, particletweaks, placeholder-api, pride, reeses-sodium-options, rrls, skinlayers3d, sodium, sodium-extra, sodium-no-alerts, sodiumextrainformation, sodiumextras (incompatible), sodiumleafculling (incompatible), sodiumoptionsapi (incompatible), sound_physics_remastered, spruceui, sspb, toadlib, viafabricplus, voicechat, wi_zoom, yet_another_config_lib_v3 (incompatible), zoomify, classic_icons, continuity:default, continuity:glass_pane_culling_fix, file/Prideful Parrots (Pansexual) (incompatible), file/Prideful Parrots (Non-Binary) (incompatible), file/pan.zip (incompatible), file/FemPack.zip, file/NeverPack.zip (incompatible)
	Current Language: en_us
	Locale: en_DE
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

**Comment by kerudion** [comment]
Hi! Fixed in the 2.0.0 releases.
