### ISSUE TITLE
[BUG]: Required dependency combo not possible.

### ISSUE THREAD

**Issue by Kishku7** [kerudion/chunksfadein#97]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

Chunks Fade In v2.0.0 requires Sodium 0.6.0 beta 4, however beta 4 was not released for Minecraft Java 1.21.0. The last available was Beta 2 released September 15th, 2024.

Chunks FI is listed as compatible with Minecraft 1.21.0

Either the compatibility with 1.21 needs to be removed, or an older beta of sodium needs to be required.

### Steps to reproduce

Install Java 1.21 client, Sodium (Modrinth will automatically choose 0.6.0 b2), and Chunks Fade in (Modrinth will choose v2 as its listed as compatible).

**Comment by kerudion** [comment]
Hello!
1.21 and 1.21.1 have really little difference, so I'm sure that you can run all your mods on 1.21.1 too. Even 1.21 and 1.21.1 clients/servers can join each other without any problems.

**Comment by Kishku7** [comment]
What I will do is stop using your mod and stop recommending it to my followers. It was a simple fix. this is lazy and your apathy shows.

**Comment by kerudion** [comment]
Sorry, looks like I misunderstood your request in the first place. And yes, I'm indeed very lazy and apathetic sometimes :)

But still, I don't want to lie that v2.0.0-1.21 doesn't support Minecraft 1.21 and Sodium beta 4. In Sodium beta 4 code it is said that it does support Minecraft 1.21 and 1.21.1:
https://github.com/CaffeineMC/sodium/blob/7b77a83d8a47ca9e550c7ebbd62cb616e42119b5/buildSrc/src/main/kotlin/BuildConfig.kt#L14
https://github.com/CaffeineMC/sodium/blob/7b77a83d8a47ca9e550c7ebbd62cb616e42119b5/fabric/src/main/resources/fabric.mod.json#L73

So I think that this is more of a release error on the part of the developer of Sodium.

I totally get it if you're still upset and angry at me.

**Comment by kerudion** [comment]
Fixed in 2.0.2-1.21.
