### ISSUE TITLE
[BUG]: v2.0.0-1.21 for Fabric will still pop up an update reminder, the link points to v2.0.0-1.21 for NeoForge

### ISSUE THREAD

**Issue by Gholts** [kerudion/chunksfadein#98]
### Before creating an issue, please make sure you have checked the following:

- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] This issue does not appear without Chunks Fade In installed.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

v2.0.0-1.21 for Fabric will still pop up an update reminder, the link points to v2.0.0-1.21 for NeoForge，Even if you turn off Update notifier
![image](https://github.com/user-attachments/assets/74510493-3242-4631-8b35-a22ff4b2881e)
![image](https://github.com/user-attachments/assets/ee199107-9b3a-4039-8ed2-76c7591b5127)

### Steps to reproduce

Just go into any saves

### Logs

[latest.log](https://github.com/user-attachments/files/17617241/latest.log)
[2024-11-04-5.log.gz](https://github.com/user-attachments/files/17617245/2024-11-04-5.log.gz)

**Comment by Gholts** [comment]
Just to add
![image](https://github.com/user-attachments/assets/80e8fe84-0d23-4d88-984d-b657de7cd69e)

**Comment by Thijzert123** [comment]
Same issue here.

**Comment by kerudion** [comment]
Hello! Fixed in v2.0.1.
