### ISSUE TITLE
[BUG]: Does not work with latest iris version iris-fabric-1.8.0-beta.7+mc1.21.1

### ISSUE THREAD

**Issue by Tom1817** [kerudion/chunksfadein#99]
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

When toggling shaders on with Iris, they fail to load. I spoke to Iris devs in their discord and they helped me identify that ChunksFadeIn is not updated to properly work with the new Iris. My latest.log showing the shader toggle issue is attached:

[latest.log](https://github.com/user-attachments/files/17623731/latest.log)

MC version: 1.21.1
Fabric loader: 1.16.9 (latest)
Iris version: iris-fabric-1.8.0-beta.7+mc1.21.1
Sodium version: sodium-fabric-0.6.0-beta.4+mc1.21.1
ChunksFadeIn version: chunksfadein-fabric-2.0.0-1.21

### Steps to reproduce

Toggle shaders on with Iris + Sodium + ChunksFadeIn

### Logs

[latest.log](https://github.com/user-attachments/files/17623738/latest.log)

**Comment by Thijzert123** [comment]
Yes, same issue
